### ISSUE TITLE
Error while using

### ISSUE THREAD

**Issue by The-One-Who-Speaks-and-Depicts** [transitive-bullshit/puppeteer-lottie-cli#14]
I am terribly sorry that I disturb you on the point, but at the point I am feeling like I am hitting the brick wall.

I have an error, while trying to convert file from lottie/json to gif. What can I do with it, if anything?

JSON file that I am trying to convert is attached, as well as archived screenshot of terminal output.

[result.zip](https://github.com/transitive-bullshit/puppeteer-lottie-cli/files/4366858/result.zip)

![image](https://user-images.githubusercontent.com/31735635/77272518-80e26f80-6cc2-11ea-9eeb-cbc295769068.png)

**Comment by transitive-bullshit** [comment]
I highly recommend using a unix machine if at all possible (whether it's a VM, macOS, or linux).

It looks like `gifski` is failing in your output. Is `gifski` installed and working locally?

Your other option if gifski isn't working for you is to output single frames and then concat then in a separate process into a GIF using some other solution.

**Comment by The-One-Who-Speaks-and-Depicts** [comment]
Ok, unix it shall be.
Gifski is installed. I didn't test it separately, though, so I cannot be sure it _works_. 
The solution with frame-by-frame approach seems promising, thank you!

**Comment by transitive-bullshit** [comment]
You're welcome 😄

Feel free to update this issue or re-open if you have additional questions. If you find a workaround, please add a comment to this issue to help others who find themselves in a similar situation.
